FROM ruby:2.3.6

RUN apt-get update -qq && apt-get install -y build-essential libpq-dev nodejs

ENV RAILS_ROOT /app

RUN mkdir -p $RAILS_ROOT
WORKDIR $RAILS_ROOT

RUN echo 'gem: --no-ri --no-rdoc' > ~/.gemrc

COPY Gemfile $RAILS_ROOT/Gemfile
COPY Gemfile.lock $RAILS_ROOT/Gemfile.lock
RUN gem install bundler && bundle install --jobs 20 --retry 5

COPY . $RAILS_ROOT

ENTRYPOINT ["./docker-entrypoint.sh"]
EXPOSE 3000

CMD ["bin/rails", "s", "-p", "3000", "-b", "0.0.0.0"]
